arkdown: kramdown
title: BioHackrXiv Preprints
description: Preprints for BioHackathons
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://egonw.github.io/bh-demo/" # the base hostname & protocol for your site, e.g. http://example.com
social:
  - title: GitHub
    platform: github
    user_url: https://github.com/biohackrxiv

# Build settings
theme: minima
paginate: 7
show_excerpts: true
plugins:
  - jekyll-feed
  - jekyll/mastodon_webfinger
  - jekyll-paginate

feed:
  tags: true
  path: feed2.xml

tags:
